name: CSS Mantenible - Un enfoque para escribir CSS de forma modular, escalable y mantenible | By Adam Silver
markdown: kramdown
url: https://maintainablecss.com
include: ['_pages']
collections:
  chapters:
    output: true
    permalink: /:collection/:title/
description: CSS Mantenible es un enfoque para escribir CSS de forma modular, escalable y mantenible.
sass:
  sass_dir: assets/_sass  